CREATE TABLE cartorio (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    cep         CHAR(8) NOT NULL,
    rua         VARCHAR(150) NOT NULL,
    numero      VARCHAR(6) NOT NULL,
    complemento VARCHAR(100),
    bairro      VARCHAR(100),
    cidade      VARCHAR(100) NOT NULL,
    uf          CHAR(2) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE certidao (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE cartorio_certidao (
    cartorio_id   BIGINT NOT NULL,
    certidao_id  BIGINT NOT NULL,
    PRIMARY KEY (cartorio_id, certidao_id),
    CONSTRAINT fk_cartorio_certidao_cartorio
        FOREIGN KEY (cartorio_id) REFERENCES cartorio (id) ON DELETE CASCADE,
    CONSTRAINT fk_cartorio_certidao_certidao
        FOREIGN KEY (certidao_id) REFERENCES certidao (id) ON DELETE CASCADE
);